name: "Build and install"

# Event for the workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - feat/**
      - fix/**

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.1.7
      - name: Build
        run: npm build

      - name: install
        run: npm install
