name: learn-github-actions

# Events for the workflow
 on:
  workflow_dispatch:
   pull_request:
    branches:
      - main
      - feat/**
      - fix/**
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.19.0"
      - run: npm install
      run: npm install
